service:
  name: pharma-search
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  stage: dev
  region: eu-central-1

functions:
  hello:
    handler: src/handlers/handler.hello
    events:
      - http:
          method: get
          path: hello

  importFile:
    handler: src/handlers/importFile.importFile
    events:
      - s3: fda-files
        event: s3:ObjectCreated:*
