service:
  name: pharma-search
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  stage: dev
  region: eu-central-1
  vpc:
    securityGroupIds:
      - sg-09219f1303373f9b1
    subnetIds:
      - subnet-c3dc31bf
      - subnet-c43087ae
      - subnet-e4ad5da8

package: # Optional deployment packaging configuration
  include: # Specify the directories and files which should be included in the deployment package
    - src/server/**
    - src/client/**

functions:
  importFile:
    handler: src/server/handlers/importFile.importFile
    timeout: 900
    environment:
      TYPEORM_HOST: ${ssm:/fda-search-db-host~true}
      TYPEORM_DATABASE: ${ssm:/fda-search-db-name~true}
      TYPEORM_USERNAME: ${ssm:/fda-search-db-username~true}
      TYPEORM_PASSWORD: ${ssm:/fda-search-db-password~true}
    events:
      - s3: ${file(./config.json):s3.bucket}
        event: s3:ObjectCreated:CompleteMultipartUpload*

  search:
    handler: src/server/handlers/searchPage.search
    environment:
      TYPEORM_HOST: ${ssm:/fda-search-db-host~true}
      TYPEORM_DATABASE: ${ssm:/fda-search-db-name~true}
      TYPEORM_USERNAME: ${ssm:/fda-search-db-username~true}
      TYPEORM_PASSWORD: ${ssm:/fda-search-db-password~true}
    events:
      - http:
          path: search
          method: get
      - http:
          path: search
          method: post

